config_path = "/Users/philippmatthes/Desktop/predict/main/src/static/configuration"
data_path = "/Users/philippmatthes/Desktop/predict/main/src/static/data"
models_path = "/Users/philippmatthes/Desktop/predict/main/src/static/logdir/models"
sessions_path = "/Users/philippmatthes/Desktop/predict/main/src/static/logdir/sessions"
logdir_path = "/Users/philippmatthes/Desktop/predict/main/src/static/logdir"
